import { Item } from './types';

let nextId = 26;

export function getNextId(): number {
  return nextId++;
}

// Placeholder image URLs (picsum.photos with seeded IDs for consistency)
const placeholders = {
  electronics: [
    'https://picsum.photos/seed/elec1/600/400',
    'https://picsum.photos/seed/elec2/600/400',
    'https://picsum.photos/seed/elec3/600/400',
    'https://picsum.photos/seed/elec4/600/400',
    'https://picsum.photos/seed/elec5/600/400',
  ],
  auto: [
    'https://picsum.photos/seed/auto1/600/400',
    'https://picsum.photos/seed/auto2/600/400',
    'https://picsum.photos/seed/auto3/600/400',
    'https://picsum.photos/seed/auto4/600/400',
  ],
  real_estate: [
    'https://picsum.photos/seed/real1/600/400',
    'https://picsum.photos/seed/real2/600/400',
    'https://picsum.photos/seed/real3/600/400',
  ],
};

export const items: Item[] = [
  {
    id: 1,
    category: 'electronics',
    title: 'MacBook Pro 16"',
    description: 'Продаю свой MacBook Pro 16" (2021) на чипе M1 Pro. Состояние отличное, работал бережно. Мощности хватает на всё: от сложного монтажа до кода, при этом ноутбук почти не греется.',
    price: 64000,
    params: { type: 'laptop', brand: 'Apple', model: 'MacBook Pro M1 Pro', condition: 'used', color: 'Серый' },
    images: [placeholders.electronics[0], placeholders.electronics[1], placeholders.electronics[2]],
    createdAt: '2025-03-10T22:39:00.000Z',
    updatedAt: '2025-03-10T23:12:00.000Z',
  },
  {
    id: 2,
    category: 'electronics',
    title: 'iPhone 17 Pro Max',
    description: 'Новый iPhone 17 Pro Max в отличном состоянии. Полный комплект, коробка, документы. Куплен в официальном магазине.',
    price: 107000,
    params: { type: 'phone', brand: 'Apple', model: 'iPhone 17 Pro Max', condition: 'new', color: 'Титановый' },
    images: [placeholders.electronics[3], placeholders.electronics[4]],
    createdAt: '2025-03-12T10:20:00.000Z',
  },
  {
    id: 3,
    category: 'electronics',
    title: 'Наушники Sony WH-1000XM5',
    description: 'Беспроводные наушники с шумоподавлением',
    price: 2990,
    params: { type: 'misc', brand: 'Sony', model: 'WH-1000XM5' },
    images: [],
    createdAt: '2025-03-15T14:30:00.000Z',
  },
  {
    id: 4,
    category: 'electronics',
    title: 'iPad Air 11, 2024 г.',
    description: 'Новый iPad Air 2024 года. Чип M2, 256GB, Wi-Fi. Идеален для учебы и творчества.',
    price: 37000,
    params: { type: 'laptop', brand: 'Apple', model: 'iPad Air M2', condition: 'new', color: 'Синий' },
    images: [],
    createdAt: '2025-03-14T18:45:00.000Z',
  },
  {
    id: 5,
    category: 'auto',
    title: 'Volkswagen Polo',
    description: 'Автомобиль в хорошем состоянии, обслуживался у дилера.',
    price: 1100000,
    params: { brand: 'Volkswagen', model: 'Polo' },
    images: [],
    createdAt: '2025-03-10T09:00:00.000Z',
  },
  {
    id: 6,
    category: 'real_estate',
    title: 'Студия, 25м²',
    description: 'Уютная студия в центре города. Свежий ремонт, мебель, техника. Тихий двор, рядом метро и парк.',
    price: 15000000,
    params: { type: 'flat', address: 'Москва, ул. Тверская, д. 15', area: 25, floor: 3 },
    images: [placeholders.real_estate[0], placeholders.real_estate[1], placeholders.real_estate[2]],
    createdAt: '2025-03-11T12:15:00.000Z',
  },
  {
    id: 7,
    category: 'real_estate',
    title: '1-комнатная квартира, 44м²',
    description: 'Однокомнатная квартира с ремонтом',
    price: 19000000,
    params: { type: 'flat' },
    images: [],
    createdAt: '2025-03-13T16:30:00.000Z',
  },
  {
    id: 8,
    category: 'auto',
    title: 'Omoda C5',
    description: 'Новый кроссовер Omoda C5. Полная комплектация, все опции. Гарантия от производителя.',
    price: 2900000,
    params: { brand: 'Omoda', model: 'C5', yearOfManufacture: 2024, transmission: 'automatic', mileage: 0, enginePower: 150 },
    images: [placeholders.auto[0], placeholders.auto[1], placeholders.auto[2], placeholders.auto[3]],
    createdAt: '2025-03-12T11:00:00.000Z',
  },
  {
    id: 9,
    category: 'electronics',
    title: 'Marshall MAJOR VI',
    description: 'Беспроводные наушники Marshall в классическом дизайне. До 100 часов автономной работы.',
    price: 20000,
    params: { type: 'misc', brand: 'Marshall', model: 'MAJOR VI', condition: 'new', color: 'Черный' },
    images: [],
    createdAt: '2025-03-15T08:20:00.000Z',
  },
  {
    id: 10,
    category: 'auto',
    title: 'Toyota Camry',
    description: 'Надежный седан в отличном состоянии',
    price: 3900000,
    params: { brand: 'Toyota', model: 'Camry' },
    images: [],
    createdAt: '2025-03-14T13:45:00.000Z',
  },
  {
    id: 11,
    category: 'electronics',
    title: 'Samsung Galaxy S24 Ultra',
    description: 'Флагманский смартфон Samsung с AI-функциями. Память 512GB, стилус S Pen в комплекте.',
    price: 89000,
    params: { type: 'phone', brand: 'Samsung', model: 'Galaxy S24 Ultra', condition: 'new', color: 'Фиолетовый' },
    images: [placeholders.electronics[1], placeholders.electronics[3]],
    createdAt: '2025-03-09T15:30:00.000Z',
  },
  {
    id: 12,
    category: 'auto',
    title: 'Lada Vesta SW Cross',
    description: '',
    price: 1600000,
    params: { brand: 'Lada', model: 'Vesta SW Cross', yearOfManufacture: 2023, transmission: 'manual' },
    images: [],
    createdAt: '2025-03-08T10:00:00.000Z',
  },
  {
    id: 13,
    category: 'real_estate',
    title: '2-комнатная квартира, 68м²',
    description: 'Просторная двухкомнатная квартира в новостройке. Панорамные окна, два санузла, подземный паркинг.',
    price: 28000000,
    params: { type: 'flat', address: 'Москва, Пресненская набережная, д. 8', area: 68, floor: 17 },
    images: [placeholders.real_estate[1], placeholders.real_estate[0], placeholders.real_estate[2]],
    createdAt: '2025-03-07T09:15:00.000Z',
  },
  {
    id: 14,
    category: 'electronics',
    title: 'PlayStation 5 Slim',
    price: 45000,
    params: { type: 'misc', brand: 'Sony', model: 'PS5 Slim' },
    images: [],
    createdAt: '2025-03-06T20:00:00.000Z',
  },
  {
    id: 15,
    category: 'auto',
    title: 'BMW X5 xDrive40i',
    description: 'Премиальный кроссовер BMW X5 в максимальной комплектации. Пневмоподвеска, панорамная крыша, Harman Kardon.',
    price: 8500000,
    params: { brand: 'BMW', model: 'X5 xDrive40i', yearOfManufacture: 2022, transmission: 'automatic', mileage: 35000, enginePower: 340 },
    images: [placeholders.auto[2], placeholders.auto[0], placeholders.auto[1]],
    createdAt: '2025-03-05T14:30:00.000Z',
  },
  {
    id: 16,
    category: 'real_estate',
    title: 'Дом 150м² с участком',
    description: 'Загородный дом в коттеджном поселке. 3 спальни, 2 санузла, гараж на 2 машины. Участок 10 соток.',
    price: 35000000,
    params: { type: 'house', address: 'Московская область, Истринский район', area: 150 },
    images: [],
    createdAt: '2025-03-04T11:00:00.000Z',
  },
  {
    id: 17,
    category: 'electronics',
    title: 'Робот-пылесос Roborock S8 Pro',
    description: 'Умный робот-пылесос с функцией мытья полов. Лидар-навигация, автоочистка щетки.',
    price: 55000,
    params: { type: 'misc', brand: 'Roborock', model: 'S8 Pro Ultra', condition: 'new', color: 'Белый' },
    images: [],
    createdAt: '2025-03-03T17:45:00.000Z',
  },
  {
    id: 18,
    category: 'auto',
    title: 'Kia K5',
    price: 2800000,
    params: { brand: 'Kia', model: 'K5', yearOfManufacture: 2024, transmission: 'automatic' },
    images: [],
    createdAt: '2025-03-02T08:30:00.000Z',
  },
  {
    id: 19,
    category: 'real_estate',
    title: 'Комната в коммуналке, 18м²',
    price: 3500000,
    params: { type: 'room', area: 18 },
    images: [],
    createdAt: '2025-03-01T13:20:00.000Z',
  },
  {
    id: 20,
    category: 'electronics',
    title: 'Xiaomi 14 Pro',
    description: 'Топовый смартфон Xiaomi с камерой Leica. Snapdragon 8 Gen 3, 512GB.',
    price: 62000,
    params: { type: 'phone', brand: 'Xiaomi', model: '14 Pro', condition: 'new' },
    images: [],
    createdAt: '2025-02-28T19:00:00.000Z',
  },
  {
    id: 21,
    category: 'auto',
    title: 'Hyundai Tucson',
    description: 'Кроссовер Hyundai Tucson 2023 года. Дизель, полный привод, пробег 20 000 км.',
    price: 3200000,
    params: { brand: 'Hyundai', model: 'Tucson', yearOfManufacture: 2023, transmission: 'automatic', mileage: 20000, enginePower: 186 },
    images: [],
    createdAt: '2025-02-27T10:15:00.000Z',
  },
  {
    id: 22,
    category: 'real_estate',
    title: '3-комнатная квартира, 95м²',
    description: 'Просторная трёхкомнатная квартира в сталинском доме. Высокие потолки, два балкона.',
    price: 42000000,
    params: { type: 'flat', address: 'Москва, Кутузовский проспект, д. 26', area: 95, floor: 5 },
    images: [placeholders.real_estate[2], placeholders.real_estate[1]],
    createdAt: '2025-02-26T16:40:00.000Z',
  },
  {
    id: 23,
    category: 'electronics',
    title: 'Dell XPS 15',
    description: 'Ультрабук Dell XPS 15 с OLED-экраном. Intel Core i7-13700H, 32GB RAM, 1TB SSD.',
    price: 120000,
    params: { type: 'laptop', brand: 'Dell', model: 'XPS 15 9530', condition: 'used', color: 'Серебристый' },
    images: [],
    createdAt: '2025-02-25T12:00:00.000Z',
  },
  {
    id: 24,
    category: 'auto',
    title: 'Chery Tiggo 7 Pro Max',
    description: '',
    price: 2400000,
    params: { brand: 'Chery', model: 'Tiggo 7 Pro Max', yearOfManufacture: 2024 },
    images: [],
    createdAt: '2025-02-24T09:30:00.000Z',
  },
  {
    id: 25,
    category: 'real_estate',
    title: 'Апартаменты у моря, 55м²',
    description: 'Апартаменты с видом на море в Сочи. Полностью меблированы, бассейн, спортзал на территории комплекса.',
    price: 18000000,
    params: { type: 'flat', address: 'Сочи, ул. Приморская, д. 3', area: 55, floor: 8 },
    images: [],
    createdAt: '2025-02-23T14:00:00.000Z',
  },
];
